service: serverless-crud

frameworkVersion: "3"

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  runtime: nodejs18.x
  region: us-east-1
  environment:
    tableName: ${self:custom.tableName}
  httpApi:
    cors: true

custom: ${file(yml/custom.yml):custom}
functions: ${file(yml/functions.yml):functions}
package: ${file(yml/package.yml):package}
plugins: ${file(yml/plugins.yml):plugins}
resources: ${file(yml/resources.yml):resources}